In [8]:
temperaturas = [2, 7, 9]
promedio = sum(temperaturas) / len(temperaturas)
promedio

6.0

In [9]:
promedio

6.0

In [19]:
import pandas as pd

In [18]:
simpson=pd.read_csv("SimpsonsData.csv")
simpson

,Season,Title,Airdate,Rating,Vote_count,Description
0,1,Simpsons Roasting on an Open Fire,17 Dec. 1989,8.2,5633.0,The family is forced to spend all of their sav...
1,1,Bart the Genius,14 Jan. 1990,7.7,3580.0,Bart ends up at a school for gifted children a...
2,1,Homer's Odyssey,21 Jan. 1990,7.4,3145.0,"After losing his job, Homer contemplates endin..."
3,1,There's No Disgrace Like Home,28 Jan. 1990,7.7,3087.0,After being embarrassed by the rest of the fam...
4,1,Bart the General,4 Feb. 1990,8.0,3130.0,After being beaten up by Nelson Muntz one too ...
...,...,...,...,...,...,...
679,31,Warrin' Priests,26 Apr. 2020,6.0,332.0,Reverend Lovejoy investigates the mysterious p...
680,31,Warrin' Priests Part 2,3 May 2020,5.7,296.0,"In Michigan, Reverend Lovejoy learns the true ..."
681,31,The Hateful Eight-Year-Olds,10 May 2020,6.7,277.0,Lisa joins a group of rich girls when she make...
682,31,The Way of the Dog,17 May 2020,7.4,288.0,The Simpsons explore the tragic past of Santa'...
683,32,Episode #32.1,27 Sep. 2020,NaN,NaN,Know what this is about? Be the first one to a...

In [20]:
type(simpson)

pandas.DataFrame

In [25]:
# calificaciones = simpson["Rating"]
calificaciones = simpson[["Rating"]]
calificaciones

     Rating
0       8.2
1       7.7
2       7.4
3       7.7
4       8.0
..      ...
679     6.0
680     5.7
681     6.7
682     7.4
683     NaN

[684 rows x 1 columns]